CREATE DATABASE Sprint1_2019

USE Sprint1_2019

CREATE TABLE ESPECIALIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
);

CREATE TABLE CLINICAS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,ENDERECO VARCHAR(255) NOT NULL
	,CNPJ CHAR(14) NOT NULL UNIQUE
	,RAZAO_SOCIAL VARCHAR(255) NOT NULL UNIQUE
	,HORARIO_FUNCIONAMENTO INT NOT NULL
);

CREATE TABLE TIPO_USUARIO(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY
	,EMAIL VARCHAR(255) NOT NULL UNIQUE
	,SENHA VARCHAR(255) NOT NULL
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIO(ID) NOT NULL
);

CREATE TABLE MEDICOS(
	ID INT IDENTITY PRIMARY KEY
	,CRM CHAR(5) NOT NULL
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL
	,ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID) NOT NULL
	,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICAS(ID) NOT NULL
);

CREATE TABLE PRONTUARIO(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL
	,DATA_NASCIMENTO DATETIME NOT NULL
	,TELEFONE CHAR(12) NOT NULL UNIQUE
	,RG CHAR(9) NOT NULL UNIQUE
	,CPF CHAR(11) NOT NULL UNIQUE
	,ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE SITUACAO(
	ID INT IDENTITY PRIMARY KEY
	,STATU CHAR(9) NOT NULL UNIQUE
);

CREATE TABLE CONSULTAS(
	ID INT IDENTITY PRIMARY KEY
	,ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIO(ID) NOT NULL
	,ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID) NOT NULL
	,DATA_CONSULTA DATETIME NOT NULL
	,ID_SITUACAO INT FOREIGN KEY REFERENCES SITUACAO(ID) NOT NULL
	,DESCRICAO VARCHAR(255)
);
